work_directory: ./tmp
repositories:
  - name: dummy-for-git-sync
    repo1: https://gitup.uni-potsdam.de/CRC1294/Z03/dummy-for-git-sync.git
    repo2: https://git.overleaf.com/5e186f8ce6368a000147cb91
